apiVersion: v1
kind: Service
metadata:
  name: zlapka-event
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: zlapka-event_mapping
      host: event.zlapka.pl
      prefix: /
      service: zlapka-event:10801
spec:
  type: NodePort
  selector:
    app: zlapka
  ports:
  - name: http
    protocol: TCP
    port: 10801
    nodePort: 32222
