apiVersion: v1
kind: Service
metadata:
  name: zlapka-event
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: zlapka-event-service_mapping
      host: event.zlapka.pl
      prefix: /
      service: zlapka-event:80
spec:
  type: NodePort
  selector:
    app: tx-manager
  ports:
  - name: http
    protocol: TCP
    port: 80
