apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-component
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-manager
      name: event-component
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tx-manager
        name: event-component
    spec:
      containers:
      - name: event-component
        image: pirat0x77/zlapka-event-component-0.1:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
